Add terms for JIRA ticket #129
nf-osi/nf-metadata-dictionary pull request #146
Opened 2022-05-16 17:08 UTC by anngvu

- **Merge https://github.com/nf-osi/nf-metadata-dictionary/pull/145 first**
- Pull changes from main into this PR
- Merge this PR
- Create new minor release
- Watch CI/CD workflow triggered with new published release

2022-05-17 16:42 UTC, allaway requested changes

2022-05-17 16:42 UTC, allaway commented on NF.csv
> -chromatin accessibility, cell surface proteins, immune clonotype, antigen specificity, and CRISPR perturbation screens.",,,FALSE,https://www.10xgenomics.com/chromium-x,platform,,,,Chromium_X,Class,As
Good catch! Not sure when this linebreak was introduced!

2022-05-17 16:42 UTC, allaway commented on NF.csv
>  platform,"A sequencing platform, microscope, spectroscope/plate reader, or other platform for collecting data. ","HiSeq3000, HiSeq2500, HiSeq4000, NextSeq500, HiSeq2000, MiSeq, Zeiss LSM 980, Affy5.0
```suggestion
platform,"A sequencing platform, microscope, spectroscope/plate reader, or other platform for collecting data. ","HiSeq3000, HiSeq2500, HiSeq4000, NextSeq500, HiSeq2000, MiSeq, Zeiss LSM 980, Affy5.0, Affy6.0, PacBioRSII, GAIIx, Illumina_HumanOmni1-Quadv1.0, Illumina_1M, Illumina_h650, Illumina_Omni2pt5M, Illumina_Omni5M, Illumina MouseWG-6 v2.0 expression beadchip, Perlegen300Karray, Agilent44Karray, IlluminaWholeGenomeDASL, IlluminaHumanHap300, NanostringnCounter, LTQOrbitrapXL, IlluminaHumanMethylation450, Illumina Infinium MethylationEPIC BeadChip, AffymetrixU133AB, Affymetrix Human Gene 1.0 ST Array, AffymetrixU133Plus2, HiSeqX, Bionano Irys, Infinium HumanOmniExpressExome, NextSeq 550, NextSeq 1000, NextSeq 2000, PacBio Sequel IIe System, PacBio Sequel II System, NanostringGeoMx, LI-COR Odyssey CLx, Spectramax M Series, Olympus DP80, Orbitrap Fusion Lumos Tribrid, Illumina NovaSeq 6000, Chromium X,EnVision 2103 Multiplate Reader",,FALSE,https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=read_group&anchor=platform,experimentalData,,,,platform,Property,Assay,annotationProperty,,Platform,,
```

2022-05-17 16:42 UTC, allaway commented on NF.csv
> +Nf2-/- Schwann cell line,"A Nf2-/- mouse schwann cell line","","",FALSE,"",modelSystemName,,"","",Nf2-/-Schwann,Class,Biosample,Model_System,Cell_Line_Model,"","",""
I have a couple of requests for these: 
- can you ask Roberta if there are more specific names for these cell lines? These are really vague
- can you ask Roberta if these cell lines are published in the literature or listed on cellosaurus? If so, we should default to the name listed on Cellosaurus. 

e.g. is this one https://web.expasy.org/cellosaurus/CVCL_7691 or https://web.expasy.org/cellosaurus/CVCL_JK03?

2022-05-17 16:42 UTC, allaway commented on NF.csv
> +hTERT meningioma,"A human meningioma cell line that has been used in drug screening","","",FALSE,"",modelSystemName,,"","",hTERT_meningioma_arachnoid,Class,Biosample,Model_System,Cell_Line_Model,"","
probably https://web.expasy.org/cellosaurus/CVCL_1959 or https://web.expasy.org/cellosaurus/CVCL_JK01 (this lab has used this cell line in the past)

but also possibly
https://web.expasy.org/cellosaurus/CVCL_M426
https://web.expasy.org/cellosaurus/CVCL_M427
https://web.expasy.org/cellosaurus/CVCL_M428

2022-05-17 16:42 UTC, allaway commented on NF.csv
> +hTERT NF2 arachnoid,"A NF2 knock-out human arachnoid cell line developed with CRISPR that has been used in drug screening","","",FALSE,"",modelSystemName,,"","",hTERT_NF2_arachnoid,Class,Biosample,Mo
possibly derivative of AC007-hTERT? https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4627286/

2022-05-17 16:42 UTC, allaway commented on NF.csv
> +hTERT arachnoid,"A human arachnoid cell line that has been used in drug screening (suitable control for hTERT NF2 arachnoid)","","",FALSE,"",modelSystemName,,"","",hTERT_arachnoid,Class,Biosample,Mod
possibly https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4627286/ AC007-hTERT?

2022-05-17 23:55 UTC, allaway commented on NF.csv
>  platform,"A sequencing platform, microscope, spectroscope/plate reader, or other platform for collecting data. ","HiSeq3000, HiSeq2500, HiSeq4000, NextSeq500, HiSeq2000, MiSeq, Zeiss LSM 980, Affy5.0
Oops, sorry for not adding this suggestion to the correct file 🙃

2022-05-18 19:59 UTC, anngvu commented
@allaway Not sure if there can be better nomenclature for non-registered lines. How do you feel about adding the PMID to the label in order to better distinguish somewhat generic names?

2022-05-18 21:22 UTC, allaway commented
Looks great to me, thanks! I added the new modelsystemnames to the annotationProperty file.

2022-05-18 21:51 UTC, allaway commented
Ok, not sure what I did wrong to break the build.... 🤔

2022-05-18 22:17 UTC, anngvu commented
Interesting...I removed the portion (PMID:XXXX) based on a hunch and it was fine locally.

2022-05-18 22:25 UTC, allaway approved these changes

2022-05-18 22:25 UTC, merged

2022-05-18 22:25 UTC, allaway commented
LGTM, thanks!

2026-04-04 05:41 UTC, allaway commented
## NADIA Curation Report

**Synapse Project:** [syn74316154](https://www.synapse.org/#!Synapse:syn74316154)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | RNA Sequencing of murine MPNST Tumors treated with myelomodulatory agents |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor |
| dataType | geneExpression |
| assay | spatialTranscriptomics |
| species | Mus musculus |
| tumorType | Malignant Peripheral Nerve Sheath Tumor |
| platform | 10x Visium |
| studyLeads | Siddhi N Paudel, Timothy P Cripe |
| institutions | Nationwide Childrens Hospital Columbus |
| fundingAgency | NCI NIH HHS |
| pmid | 39044819 |
| doi | 10.3389/fimmu.2024.1384623 |
| alternateDataRepository | geo:GSE244829, insdc.sra:PRJNA1024972 |

### Curation Notes
- GPL24247 = 10x Genomics Visium spatial transcriptomics platform
- assay corrected to spatialTranscriptomics (not rnaSeq)
- 23 FASTQ files in Raw Data folder
- manifestation corrected: removed Juvenile Myelomonocytic Leukemia (wrong for murine MPNST study)
- studyLeads corrected from LastName-First to FirstName-Last

**Status:** pendingReview ✓