Patch templates props
nf-osi/nf-metadata-dictionary pull request #358
Opened 2023-10-17 19:25 UTC by cconrad8

2023-10-17 19:25 UTC, cconrad8 commented
I'm not sure if specimenID should be required now..I've since come across situations where it's not surfaced and I'm not sure what to put in that situation.

2023-10-19 19:50 UTC, cconrad8 commented
@anngvu Yeah I think i was the one that requested it to be made required before.... 😬
It's for this project: https://docs.google.com/spreadsheets/d/1rFuEeLYO-WNeVOBppb3TYaLm7YO1Pe1PMPC57hAPlIw/edit
The excel files don't have IDs

Is there a way to make the terms required in one but not required in the other?

2023-10-19 22:09 UTC, anngvu commented
Hmm, one of the files is not really raw data -- just summarized data with bar charts -- I think we should move syn52522934 to  Analysis since it's not really meant for the Imaging Assay template. The other [syn52522936](https://www.synapse.org/#!Synapse:syn52522936) looks more like clinical results data (REDCAP export). So I think we can use the Clinical Assay here, which doesn't ask for specimenID. But still need individualIDs. Is it possible to ask them about the deidentified ids associated with this data?

2023-10-24 20:14 UTC, anngvu requested changes

2023-10-24 20:14 UTC, anngvu commented on modules/props.yaml
> +    required: false
Change back to `true`.

2023-10-30 19:18 UTC, cconrad8 commented on modules/props.yaml
> +    required: false
this has been changed back to true

2023-10-30 22:42 UTC, allaway commented
LGTM!

2023-10-30 22:43 UTC, allaway approved these changes

2023-10-30 23:37 UTC, anngvu approved these changes

2023-10-30 23:37 UTC, merged