Reconceptualized biosample data collection
nf-osi/nf-metadata-dictionary pull request #395
Opened 2024-02-02 17:40 UTC by anngvu

See #334. This is significant and would require a lot of changes in other templates as well as downstream operationally, so it's only 5% of what would need to happen if we really want to switch over collecting biosamples in this approach. I think switching over wholesale for NF is going to be tricky because it's very different from HTAN/Gray Foundation, so I think the idea was to try this for just 1-2 selected projects that might actually benefit.

- Set up of a "Biosample" folder so data could be stored there as a file.
- Docs/education for contributors as how to use several templates
- Implementation of extracting data from files somehow so they still show up in the portal.
- Implementation of cross-validation

2024-02-20 13:47 UTC, cconrad8 commented
Nice! it looks like Manifestation Enum was already used here? so the drop downs in the google sheet are showing up with the manifestations rather than what was intended? 
![image](https://github.com/nf-osi/nf-metadata-dictionary/assets/114612268/7391301a-4c6d-410c-8490-e2d8592dd699)
  https://github.com/nf-osi/nf-metadata-dictionary/blob/494fe54ffb2e89c360d010f4296006b5fbf80ae5/modules/DCC/Portal.yaml#L63

2024-02-20 13:50 UTC, cconrad8 commented
And just as a note here that in Gray Foundation the structure is 
'Data' > 'Patient Cohort Data'> 'synapse_storage_manifest_cohortcoretemplate.csv'
in case we want to do something similar

2024-02-20 13:53 UTC, cconrad8 requested changes

2024-02-20 13:53 UTC, cconrad8 commented on modules/Sample/Diagnosis.yaml
> +  ManifestationEnum:
change to PresenceStatusEnum or something similar?

2024-02-28 21:27 UTC, allaway approved these changes
We discussed this in our 1-1. 


Key takeaways:

-this is great!
-let's consider pilot this manifest in the Sarin project and in Batch 5 of the NF1 biobank project (cc @jaybee84 )
-let's take a look at the 2023 Sundby paper for any updates that we could incorporate
-let's share with NTAP to see if we can align/adopt parts of their clinical data model 
-let's get feedback from Sundby and Rhodes on the NF1 CDM slack
-consider changing name of manifest as described in PR text (prefer Cohort over HumanIndividual) 
-this is good to merge as-is and then we can update after feedback

2024-02-29 03:23 UTC, merged